-- AlterTable
ALTER TABLE `estimate` ADD COLUMN `taxAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `taxRate` DECIMAL(10, 4) NOT NULL DEFAULT 0,
    ADD COLUMN `totalPayable` DECIMAL(12, 2) NOT NULL DEFAULT 0;
